# --- !Ups

create table "players" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "nickName" varchar not null,
  "score" int
  );

# --- !Downs

drop table "players" if exists;
